### ISSUE TITLE
utf8 encoding failed on emdash '—'

### ISSUE THREAD

**Issue by joprice** [johnwhitington/camlpdf#39]
I'm trying to use `Pdftext.utf8_of_pdfdocstring` on a string extracted from a `Pdfops.Op_Tj` after parsing a pdf file, and getting the following error:

```codepoint_of_pdfdocencoding: bad text string (char 148)```

The resulting string has invalid characters like 'Š' in place of the expected em-dashes.

**Comment by johnwhitington** [comment]
Can you supply an example file?

**Comment by joprice** [comment]
http://www.dominiopublico.gov.br/download/texto/bn000012.pdf

**Comment by johnwhitington** [comment]
This just loads a webpage for me...

**Comment by joprice** [comment]
Weird it did the same for me on one access but then worked on the next. Here's the file

[bn000012.pdf](https://github.com/johnwhitington/camlpdf/files/5202079/bn000012.pdf)

**Comment by johnwhitington** [comment]
(0x97 is the emdash in Windows Code page 1252. In unicode, 0x97 is "end of guarded area".)

The strings associated with Op_Tj are not PDF docstrings, because they are inside the page content. Instead, you have to convert them through the font encoding:

58 0 obj
<</Type/Font/Subtype/TrueType/FirstChar 32/LastChar 242/Widths[250 333 420 0 0 0 0 0 0 0 0 0 250 333 250 0 0 0 0 0 0 0 0 0 0 0 333 0 0 0 0 0 0 611 0 667 722 0 0 0 0 0 0 0 556 833 667 0 611 722 0 0 556 0 0 0 0 0 0 0 0 0 0 0 0 500 500 444 500 444 278 0 500 278 278 0 278 722 500 500 500 0 389 389 278 500 444 0 444 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 500 500 0 0 0 0 0 444 0 0 0 0 0 0 0 0 500]/Encoding/WinAnsiEncoding/BaseFont/MIHHPB+TimesNewRoman,Italic/FontDescriptor 30 0 R>>
endobj

Normally, there is a nice /ToUnicode entry to help you get straight to unicode codepoints, but not in this old-fashioned PDF. Luckily, however, although this PDF font has been subset, the codepoints have been retained (see all the 0s in the /Widths above). So you just need to convert from /WinAnsiEncoding to UTF8.

CamlPDF should have the information inside it for this -- use the tables in Pdfglyphlist.mli (perhaps inverting some of them...) to go Win codepoint --> /charname --> UTF codepoint. Then convert the sequence of UTF codepoints to UTF8 (again camlpdf can do this)

**Comment by joprice** [comment]
I'm confused how I get a hold of the font associated with the text. I tried matching on Pdfops.Op_Tf, but the font there is a string reference like "/TT2". I'm following some of the examples that use `Pdfops.parse_operators`, but maybe that's the wrong approach.

**Comment by johnwhitington** [comment]
e.g in Pdftext

```
(** Table of all the entries in an encoding. *)
val table_of_encoding : encoding -> (int, string) Hashtbl.t
```

looks useful

**Comment by joprice** [comment]
I see. I'll try that. I stared questioning my whole approach for a second.

**Comment by joprice** [comment]
Actually I followed your tips and tried out some of the functions in Pdftext, and I think it works by just using existing functions:

```ocaml

let font = lookup_font pdf page.Pdfpage.resources f in
let extractor = Pdftext.text_extractor_of_font pdf font

...

let to_utf8 content extractor =
	let codepoints =
      Pdftext.codepoints_of_text extractor content
    in
    Pdftext.utf8_of_codepoints codepoints
```

**Comment by johnwhitington** [comment]
Excellent. Looks like I need to fix `-extract-text` in cpdf then. Leaving this bug open for that purpose.
